services:

  db:
    image: postgres:16
    container_name: inventory_postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend

    container_name: inventory_backend

    depends_on:
      - db

    ports:
      - "8000:8000"

    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/inventory_db

  frontend:
    build: ./frontend

    container_name: inventory_frontend

    depends_on:
      - backend

    ports:
      - "5173:5173"

volumes:
  postgres_data: